apiVersion: apps/v1
kind: Deployment
metadata:
  name: coconote-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coconote-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: coconote-backend
    spec:
      containers:
        - name: coconote-backend
          image: 730335516193.dkr.ecr.ap-northeast-2.amazonaws.com/coconote/coconote_be:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "768Mi"  # 메모리 요청을 768Mi로 증가
              cpu: "600m"      # CPU 요청을 600m로 증가
            limits:
              memory: "1.5Gi"  # 메모리 제한을 1.5Gi로 증가
              cpu: "1.0"       # CPU 제한을 1.0으로 증가
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # Pod의 이름을 환경 변수로 설정
            - name: KAFKA_GROUP_ID
              value: "coconote-group-id-$(POD_NAME)"  # KAFKA_GROUP_ID를 설정
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: redis-port
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: db-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: db-password
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: mail-host
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: mail-port
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: mail-password
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: google-client-secret
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: kakao-client-id
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: kakao-client-secret
            - name: OPENSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: opensearch-host
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: opensearch-username
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: opensearch-password
            - name: S3_KEY
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: s3-key
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: s3-secret
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: s3-region
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: s3-bucket
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: jwt-secret
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: coconote-backend-secrets
                  key: kafka-bootstrap-server
#          # 무중단 배포를 위한 컨테이너 health check
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            # 컨테이너 시작후 지연시간 설정
#            initialDelaySeconds: 20
#            # 확인 반복 주기
#            periodSeconds: 10
#            # 요청 timeout 설정
#            timeoutSeconds: 2
#            # 성공 인식 횟수 설정
#            successThreshold: 1
#            # 연속 실패 횟수 설정 : 연속적으로 3번을 실패하면 건강하지 않은 상태로 판단하여 기존 서버 종료시키지 않음
#            failureThreshold: 3